# Generated by Django 4.2.7 on 2024-11-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userapisecret",
            name="team",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
