# Generated by Django 4.2.7 on 2024-12-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_userapisecret_team"),
    ]

    operations = [
    ]
