# Generated by Django 4.2.7 on 2024-12-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_quotarule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userapisecret",
            options={},
        ),
        migrations.AlterField(
            model_name="userapisecret",
            name="username",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="userapisecret",
            unique_together={("username", "team")},
        ),
    ]
