# Generated by Django 4.2.7 on 2025-05-09 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='配置ID')),
                ('collector', models.CharField(max_length=100, verbose_name='采集器名称')),
                ('collect_type', models.CharField(max_length=50, verbose_name='采集类型')),
                ('config_type', models.CharField(max_length=50, verbose_name='配置类型')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('is_child', models.BooleanField(default=True, verbose_name='是否子配置')),
                ('monitor_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorinstance', verbose_name='监控对象实例')),
            ],
            options={
                'verbose_name': '采集配置',
                'verbose_name_plural': '采集配置',
                'unique_together': {('monitor_instance', 'collector', 'collect_type', 'config_type')},
            },
        ),
    ]
