# Generated by Django 4.2.7 on 2025-04-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="llmskill",
            name="unique_owner_name",
        ),
        migrations.RemoveField(
            model_name="knowledgedocument",
            name="enable_excel_parse",
        ),
        migrations.RemoveField(
            model_name="knowledgedocument",
            name="enable_general_parse",
        ),
        migrations.RemoveField(
            model_name="knowledgedocument",
            name="enable_semantic_chunk_parse",
        ),
        migrations.RemoveField(
            model_name="knowledgedocument",
            name="excel_full_content_parse",
        ),
        migrations.RemoveField(
            model_name="knowledgedocument",
            name="excel_header_row_parse",
        ),
        migrations.AddField(
            model_name="embedprovider",
            name="is_build_in",
            field=models.BooleanField(default=False, verbose_name="是否内置"),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="chunk_type",
            field=models.CharField(default="fixed_size", max_length=30, verbose_name="chunk type"),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="mode",
            field=models.CharField(default="full", max_length=30, verbose_name="mode"),
        ),
        migrations.AddField(
            model_name="llmskill",
            name="is_template",
            field=models.BooleanField(default=False, verbose_name="是否模板"),
        ),
        migrations.AddField(
            model_name="llmskill",
            name="skill_type",
            field=models.IntegerField(
                choices=[(1, "Basic Tool"), (2, "Knowledge Tool")], default=1, verbose_name="技能类型"
            ),
        ),
        migrations.AddField(
            model_name="rerankprovider",
            name="is_build_in",
            field=models.BooleanField(default=False, verbose_name="是否内置"),
        ),
    ]
