# Generated by Django 4.2.7 on 2025-04-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_name", models.CharField(max_length=100, verbose_name="Task Name")),
                ("train_progress", models.FloatField(default=0, verbose_name="Train Progress")),
                ("knowledge_ids", models.JSONField(default=list, verbose_name="Knowledge IDs")),
                ("created_by", models.CharField(max_length=100, verbose_name="Created By")),
            ],
        ),
    ]
