# Generated by Django 4.2.7 on 2025-04-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0003_knowledgetask"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgetask",
            name="knowledge_base_id",
            field=models.IntegerField(default=0, verbose_name="Knowledge IDs"),
        ),
    ]
