# Generated by Django 4.2.7 on 2025-05-09 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0003_controllertasknode_status_nodecollectorinstallstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childconfig',
            name='collect_instance_id',
        ),
        migrations.AlterField(
            model_name='childconfig',
            name='collect_type',
            field=models.CharField(max_length=50, verbose_name='采集类型'),
        ),
        migrations.AlterField(
            model_name='childconfig',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='子配置ID'),
        ),
        migrations.CreateModel(
            name='NodeCollectorConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.collectorconfiguration')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.node')),
            ],
            options={
                'unique_together': {('node', 'collector_config')},
            },
        ),
        migrations.AlterField(
            model_name='collectorconfiguration',
            name='nodes',
            field=models.ManyToManyField(blank=True, through='node_mgmt.NodeCollectorConfiguration', to='node_mgmt.node', verbose_name='节点'),
        ),
    ]
