# Generated by Django 4.2.7 on 2024-08-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inst_id", models.BigIntegerField(db_index=True, verbose_name="实例ID")),
                ("model_id", models.CharField(max_length=100, verbose_name="模型ID")),
                ("label", models.CharField(max_length=50, verbose_name="标签ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("create_entity", "创建"),
                            ("delete_entity", "删除"),
                            ("update_entity", "修改"),
                            ("create_edge", "创建关联"),
                            ("delete_edge", "取消关联"),
                        ],
                        max_length=30,
                        verbose_name="变更类型",
                    ),
                ),
                ("before_data", models.JSONField(default=dict, verbose_name="变更前实例信息")),
                ("after_data", models.JSONField(default=dict, verbose_name="变更后实例信息")),
                (
                    "operator",
                    models.CharField(default="", max_length=50, verbose_name="创建者"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShowField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "created_by",
                    models.CharField(db_index=True, max_length=50, verbose_name="创建人"),
                ),
                (
                    "model_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="模型ID"
                    ),
                ),
                ("show_fields", models.JSONField(default=list, verbose_name="展示字段列表")),
            ],
            options={
                "verbose_name": "时间相关字段",
                "abstract": False,
            },
        ),
    ]
