# Generated by Django 4.2.7 on 2025-02-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmdb", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="showfield",
            options={"verbose_name": "Time Fields"},
        ),
        migrations.AlterField(
            model_name="showfield",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time"),
        ),
        migrations.AlterField(
            model_name="showfield",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
        ),
    ]
