# Generated by Django 4.2.7 on 2025-03-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb", "0003_collectmodels"),
    ]

    operations = [
        migrations.CreateModel(
            name="OidMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("model", models.CharField(max_length=128, null=True, verbose_name="设备型号")),
                ("oid", models.CharField(help_text="设备oid", max_length=64, unique=True)),
                ("brand", models.CharField(help_text="品牌", max_length=64, null=True)),
                ("device_type", models.CharField(help_text="设备类型", max_length=128)),
                ("built_in", models.BooleanField(default=False, verbose_name="是否内置")),
            ],
            options={"verbose_name": "Maintainer Fields", "abstract": False},
        ),
    ]
