# Generated by Django 4.2.7 on 2025-04-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmdb", "0004_oidmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="changerecord",
            name="message",
            field=models.TextField(default="", help_text="操作信息", verbose_name="操作信息"),
        ),
        migrations.AddField(
            model_name="changerecord",
            name="model_object",
            field=models.CharField(default="", help_text="模型对象", max_length=50, verbose_name="模型对象"),
        ),
        migrations.AlterField(
            model_name="changerecord",
            name="type",
            field=models.CharField(
                choices=[
                    ("create_entity", "创建"),
                    ("delete_entity", "删除"),
                    ("update_entity", "修改"),
                    ("execute", "执行"),
                    ("create_edge", "创建关联"),
                    ("delete_edge", "取消关联"),
                ],
                max_length=30,
                verbose_name="变更类型",
            ),
        ),
    ]
