# Generated by Django 4.2.7 on 2025-05-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_changerecord_message_changerecord_model_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectmodels',
            name='task_type',
            field=models.CharField(choices=[('vm', 'VM采集'), ('snmp', 'SNMP采集'), ('k8s', 'K8S采集'), ('cloud', '云采集'), ('protocol', '协议采集'), ('host', '主机采集'), ('middleware', '中间件采集'), ('ip', 'IP采集'), ('other', '其他采集')], help_text='任务类型', max_length=32),
        ),
    ]
