# Generated by Django 4.2.7 on 2025-04-07 03:02

import django.db.models.deletion
from django.db import migrations, models

import apps.core.mixinx


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("enterprise_wechat", "Enterprise Wechat"),
                            ("enterprise_wechat_bot", "Enterprise Wechat Bot"),
                        ],
                        max_length=30,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("description", models.TextField()),
            ],
            bases=(models.Model, apps.core.mixinx.EncryptMixin),
        ),
    ]
