# Generated by Django 4.2.7 on 2025-04-07 03:02

import django.db.models.deletion
from django.db import migrations, models

import apps.core.mixinx


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("system_mgmt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupDataRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("group_id", models.CharField(max_length=100)),
                ("group_name", models.CharField(max_length=100)),
                ("rules", models.JSONField(default=dict)),
                ("app", models.CharField(default="", max_length=50)),
            ],
            options={
                "unique_together": {("name", "group_id")},
            },
        ),
        migrations.CreateModel(
            name="UserRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=100)),
                (
                    "group_rule",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="system_mgmt.groupdatarule"),
                ),
            ],
        ),
    ]
